version: '3.4'

services:
  backendtest:
    image: backendtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4001:4001
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db
