version: '3.4'

services:
  backendtest:
    image: backendtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4001:4001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
